name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# These are the jobs or we can say the workflow that the code needs to flow for testing
jobs:
  test:
    runs-on: ubuntu-latest
    # checkout code from repository
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
    # setting up python environment
      - name: Set up Python
        uses: actions/setup-python@v3
    # installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    # running the test
      - name: Run test cases
        run: pytest


        